# Site metadata
keywords: Machine Learning, Data Science, FsQCA, Fuzzy Theory, Financial Forecasting
description: Academic Website of Mahinda Mailagaha Kumbure
title: Homepage of Mahinda Mailagaha Kumbure

author: Mahinda Mailagaha Kumbure
#authorimg: images/dd.png
authoroccup: Post-doctoral Fellow

inst: LUT University
#insturl: https://www.dfinity.org
# uni: Graz University of Technology
# uniurl: http://www.tugraz.at

vcard: 'mahinda.mailagaha.kumbure@lut.fi'
office: https://online.tugraz.at/tug_online/ris.einzelraum?raumkey=4944
#twitter: dderler
#keybase: dderler
linkedin: https://www.linkedin.com/in/mk-mahinda/
dblp: https://dblp.org/pid/264/9206.html
orcid: https://orcid.org/0000-0002-2849-4917
scholar: https://scholar.google.ru/citations?user=RlfoN20AAAAJ&hl=en&oi=ao

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
collections:
  - preprints
  - proc
  - jour
  - articles
  - theses
  - deli
  - talk
exclude:
  - Gemfile
  - Gemfile.lock
include:
  - keybase.txt
