# Site metadata
keywords: Machine Learning, Data Science, FsQCA, Fuzzy Theory, Financial Forecasting
description: Academic Website of Mahinda Mailagaha Kumbure
title: Homepage of Mahinda Mailagaha Kumbure

author: Mahinda Mailagaha Kumbure
#authorimg: images/dd.png
authoroccup: Post-doctoral Fellow

inst: LUT University
#insturl: https://www.dfinity.org
# uni: Graz University of Technology
# uniurl: http://www.tugraz.at

vcard: 'mailto:david@dfinity.org'
office: https://online.tugraz.at/tug_online/ris.einzelraum?raumkey=4944
twitter: dderler
keybase: dderler
linkedin: david-derler-08630495
dblp: hd/d/Derler:David
scholar: YfMKI0wAAAAJ

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
collections:
  - preprints
  - proc
  - jour
  - articles
  - theses
  - deli
  - talk
exclude:
  - Gemfile
  - Gemfile.lock
include:
  - keybase.txt
