# Site metadata
keywords: Cryptography, Privacy, Information Security, Digital Signatures, Graz University of Technology, IAIK
description: Academic Website of David Derler, IAIK, Graz University of Technology, Graz, Austria
title: Homepage of David Derler

author: David Derler
authorimg: images/dd.png
authoroccup: Researcher in Cryptography

inst: IAIK
insturl: http://www.iaik.tugraz.at
uni: Graz University of Technology
uniurl: http://www.tugraz.at

vcard: 'mailto:cryptsec@derler.info'
office: https://online.tugraz.at/tug_online/ris.einzelraum?raumkey=4944
twitter: dderler
keybase: dderler
linkedin: david-derler-08630495
dblp: hd/d/Derler:David
scholar: YfMKI0wAAAAJ

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
collections:
  - preprints
  - proc
  - jour
  - articles
  - theses
  - deli
  - talk
exclude:
  - Gemfile
  - Gemfile.lock
include:
  - keybase.txt
